/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EmployerDatabase;
import java.sql.*;
import javax.swing.*;
import java.text.*; 
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sahil
 */
public class EmployerDatabase extends javax.swing.JFrame {

    /**
     * Creates new form EmployerDatabase
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel model = new DefaultTableModel();  
    
    public EmployerDatabase() {
        initComponents();
        conn = EmployerDatabase.ConnectDb();
        Object col[] ={"Employee_ID", "Name","Age","Gender","Start_Date","Level","Team_Info","Position_title","Cell_Phone","Email"};
        model.setColumnIdentifiers(col);
        jTable1.setModel(model);
        
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public static Connection ConnectDb(){
        try
        {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:D:\\SOFTWARES\\DB.Browser.for.SQLite-3.12.2-win64\\DB Browser for SQLite\\Employ.db");
            return conn;
        }    
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "EmployeeID", "Name", "Age", "Gender", "Start Date", "Level", "Team Info", "Position Title", "Cell Phone ", "Email "
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 780, 370));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("EmployeeID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 200, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 200, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Age");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jTextField8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 200, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Gender");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 200, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Start Date");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jTextField10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 200, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Level");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jTextField11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 200, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Team Info");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jTextField12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 200, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Postion Title");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jTextField13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 200, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 470, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Cell Phone No");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        jTextField14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 200, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("Cell Phone");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 130, 30));

        jTextField15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jTextField15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField15KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 730, 120, 30));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton5.setText("Add Data");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 140, -1));

        jTextField16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 200, -1));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Email");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("Search With: ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 160, 30));

        jTextField17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jTextField17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField17KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, 260, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setText("Name");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, 80, 30));

        jTextField18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jTextField18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField18KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 690, 260, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setText(" ID");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 730, 40, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setText("Start Date");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 130, 30));

        jTextField19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jTextField19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField19KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 260, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setText("Email");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 70, 30));

        jTextField20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jTextField20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField20KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 260, 30));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

private JFrame frame;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm do you want to exit?", "Employee Management System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION);
        {System.exit(0);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 try{
                String sql ="DELETE from Employ where Employee_ID=? ";
                pst=conn.prepareStatement(sql);
                pst.setString(1, jTextField6.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null,"Record Deleted");

            }catch(Exception e){

                JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }
            }
                updateTable();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String sql = "INSERT INTO Employ(Employee_ID,Name,Age,Gender,Start_Date,Level,Team_Info,Position_title,Cell_Phone,Email)VALUES(?,?,?,?,?,?,?,?,?,?)";
        
        try 
        {
            pst = conn.prepareStatement(sql);
            pst.setString(1,jTextField6.getText());
            pst.setString(2,jTextField7.getText());
            pst.setString(3,jTextField8.getText());
            pst.setString(4,jTextField9.getText());
            pst.setString(5,jTextField10.getText());
            pst.setString(6,jTextField11.getText());
            pst.setString(7,jTextField12.getText());
            pst.setString(8,jTextField13.getText());
            pst.setString(9,jTextField14.getText());
            pst.setString(10,jTextField16.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Added data successfully");
            
            rs.close();
            pst.close();
        }
        catch(Exception e) 
                {
                    JOptionPane.showMessageDialog(null,e);
                }
                    updateTable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField15KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15KeyReleased
 
 try{

            String sql ="select * from Employ where Employee_ID=? ";

            pst=conn.prepareStatement(sql);
            pst.setString(1,jTextField15.getText());
            rs=pst.executeQuery();

            String add1 =rs.getString("Employee_ID");
            jTextField6.setText(add1);

            String add2 =rs.getString("Name");
            jTextField7.setText(add2);

            String add3 =rs.getString("Age");
            jTextField8.setText(add3);

            String add4 =rs.getString("Gender");
            jTextField9.setText(add4);

            String add5 =rs.getString("Start_Date");
            jTextField10.setText(add5);

            String add7 =rs.getString("Level");
            jTextField11.setText(add7);

            String add8 =rs.getString("Team_Info");
            jTextField12.setText(add8);

            String add9 =rs.getString("Position_title");
            jTextField13.setText(add9);

            String add10 =rs.getString("Cell_Phone");
            jTextField14.setText(add10);
            
            String add11 =rs.getString("Email");
            jTextField16.setText(add11);

        }
 
 catch(Exception e){
            JOptionPane.showMessageDialog(null, "No Data");
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){
                 //JOptionPane.showMessageDialog(null, "No Data");
            }
        }

    }//GEN-LAST:event_jTextField15KeyReleased

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField17KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField17KeyReleased
 
 try{

            String sql ="select * from Employ where Cell_Phone=? ";

            pst=conn.prepareStatement(sql);
            pst.setString(1,jTextField17.getText());
            rs=pst.executeQuery();

            String add1 =rs.getString("Employee_ID");
            jTextField6.setText(add1);

            String add2 =rs.getString("Name");
            jTextField7.setText(add2);

            String add3 =rs.getString("Age");
            jTextField8.setText(add3);

            String add4 =rs.getString("Gender");
            jTextField9.setText(add4);

            String add5 =rs.getString("Start_Date");
            jTextField10.setText(add5);

            String add7 =rs.getString("Level");
            jTextField11.setText(add7);

            String add8 =rs.getString("Team_Info");
            jTextField12.setText(add8);

            String add9 =rs.getString("Position_title");
            jTextField13.setText(add9);

            String add10 =rs.getString("Cell_Phone");
            jTextField14.setText(add10);
            
            String add11 =rs.getString("Email");
            jTextField16.setText(add11);

        }
 
 catch(Exception e){
            JOptionPane.showMessageDialog(null, "No Data");
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){
                 //JOptionPane.showMessageDialog(null, "No Data");
            }
        }

    }//GEN-LAST:event_jTextField17KeyReleased

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField18KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyReleased
 
 try{

            String sql ="select * from Employ where Name=? ";

            pst=conn.prepareStatement(sql);
            pst.setString(1,jTextField18.getText());
            rs=pst.executeQuery();

            String add1 =rs.getString("Employee_ID");
            jTextField6.setText(add1);

            String add2 =rs.getString("Name");
            jTextField7.setText(add2);

            String add3 =rs.getString("Age");
            jTextField8.setText(add3);

            String add4 =rs.getString("Gender");
            jTextField9.setText(add4);

            String add5 =rs.getString("Start_Date");
            jTextField10.setText(add5);

            String add7 =rs.getString("Level");
            jTextField11.setText(add7);

            String add8 =rs.getString("Team_Info");
            jTextField12.setText(add8);

            String add9 =rs.getString("Position_title");
            jTextField13.setText(add9);

            String add10 =rs.getString("Cell_Phone");
            jTextField14.setText(add10);
            
            String add11 =rs.getString("Email");
            jTextField16.setText(add11);

        }
 
 catch(Exception e){
            JOptionPane.showMessageDialog(null, "No Data");
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){
                 //JOptionPane.showMessageDialog(null, "No Data");
            }
        }

    }//GEN-LAST:event_jTextField18KeyReleased

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField19KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField19KeyReleased
 
 try{

            String sql ="select * from Employ where Start_Date=? ";

            pst=conn.prepareStatement(sql);
            pst.setString(1,jTextField19.getText());
            rs=pst.executeQuery();

            String add1 =rs.getString("Employee_ID");
            jTextField6.setText(add1);

            String add2 =rs.getString("Name");
            jTextField7.setText(add2);

            String add3 =rs.getString("Age");
            jTextField8.setText(add3);

            String add4 =rs.getString("Gender");
            jTextField9.setText(add4);

            String add5 =rs.getString("Start_Date");
            jTextField10.setText(add5);

            String add7 =rs.getString("Level");
            jTextField11.setText(add7);

            String add8 =rs.getString("Team_Info");
            jTextField12.setText(add8);

            String add9 =rs.getString("Position_title");
            jTextField13.setText(add9);

            String add10 =rs.getString("Cell_Phone");
            jTextField14.setText(add10);
            
            String add11 =rs.getString("Email");
            jTextField16.setText(add11);

        }
 
 catch(Exception e){
            JOptionPane.showMessageDialog(null, "No Data");
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){
                 //JOptionPane.showMessageDialog(null, "No Data");
            }
        }

    }//GEN-LAST:event_jTextField19KeyReleased

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField20KeyReleased
 
 try{

            String sql ="select * from Employ where Email=? ";

            pst=conn.prepareStatement(sql);
            pst.setString(1,jTextField20.getText());
            rs=pst.executeQuery();

            String add1 =rs.getString("Employee_ID");
            jTextField6.setText(add1);

            String add2 =rs.getString("Name");
            jTextField7.setText(add2);

            String add3 =rs.getString("Age");
            jTextField8.setText(add3);

            String add4 =rs.getString("Gender");
            jTextField9.setText(add4);

            String add5 =rs.getString("Start_Date");
            jTextField10.setText(add5);

            String add7 =rs.getString("Level");
            jTextField11.setText(add7);

            String add8 =rs.getString("Team_Info");
            jTextField12.setText(add8);

            String add9 =rs.getString("Position_title");
            jTextField13.setText(add9);

            String add10 =rs.getString("Cell_Phone");
            jTextField14.setText(add10);
            
            String add11 =rs.getString("Email");
            jTextField16.setText(add11);

        }
 
 catch(Exception e){
            JOptionPane.showMessageDialog(null, "No Data");
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){
                 //JOptionPane.showMessageDialog(null, "No Data");
            }
        }

    }//GEN-LAST:event_jTextField20KeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        try{

                String value1 = jTextField6.getText();
                String value2 = jTextField7.getText();
                String value3 = jTextField8.getText();
                String value4 = jTextField9.getText();
                String value5 = jTextField10.getText();
                String value6 = jTextField11.getText();
                String value7 = jTextField12.getText();
                String value8 = jTextField13.getText();
                String value9 = jTextField14.getText();
                String value10 = jTextField16.getText();


                String sql= "UPDATE Employ set Employee_ID='"
    + value1 + "',Name='" + value2 + "', Age='" + value3 + "', " + "Gender='" + value4 + "',Start_Date='" + value5 + "',Level='" + value6 + "'," + "Team_Info='" + value7 + "',Position_title='" + value8 + "', Cell_Phone = '" + value9 + "', " + "Email = '" + value10 + "', " +  "WHERE Employee_ID='" + value1 + "' ;";

                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Record Updated");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }
        }
            //updateTable();
    }//GEN-LAST:event_jButton6ActionPerformed

    

    /**
     * @param args the command line arguments
     */
    
    public void updateTable(){
        conn = EmployerDatabase.ConnectDb();
        if(conn != null)
        {
        String sql = "SELECT Employee_ID,Name,Age,Gender,Start_Date,Level,Team_Info,Position_title,Cell_Phone,Email from Employ";
        
        try 
        {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            Object[] columnData = new Object[10];
            
            while (rs.next()){
            columnData[0] = rs.getString("Employee_ID");
            columnData[1] = rs.getString("Name");
            columnData[2] = rs.getString("Age");
            columnData[3] = rs.getString("Gender");
            columnData[4] = rs.getString("Start_Date");
            columnData[5] = rs.getString("Level");
            columnData[6] = rs.getString("Team_Info");
            columnData[7] = rs.getString("Position_title");
            columnData[8] = rs.getString("Cell_Phone");
            columnData[9] = rs.getString("Email");
            model.addRow(columnData);
            
            
        }
        }
        catch(Exception e) 
                {
                    JOptionPane.showMessageDialog(null,e);
                }
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployerDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
